name: Node.js CD - Production

on:
    release:
        types: [published]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: appleboy/ssh-action@master
              name: Deploy production on VPS
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  passphrase: ${{ secrets.SERVER_PASSPHRASE }}
                  port: 22
                  script: |
                      export PATH="$PATH:/home/reginald/.nvm/versions/node/v20.11.1/bin/"
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      nvm install 20.11.1
                      cd ~/dev/repos/w3-bestiary/w3-bestiary-front
                      git checkout main
                      git fetch --all
                      git reset --hard origin/main
                      npm ci
                      npm run build
                      pm2 delete witcher-app
                      pm2 start dist/w3-bestiary-front/server/server.mjs --namespace witcher --name witcher-app
