name: Node.js CD - Preview

on:
    push:
        branches: [develop]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: appleboy/ssh-action@master
              name: Deploy preview on VPS
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                passphrase: ${{ secrets.SERVER_PASSPHRASE }}
                port: 22
                script: |
                    export PATH="$PATH:/home/reginald/.nvm/versions/node/v16.16.0/bin/"
                    export NVM_DIR=~/.nvm
                    source ~/.nvm/nvm.sh
                    nvm use --lts
                    cd ~/dev/repos/w3-bestiary/preview/w3-bestiary-front
                    git checkout develop
                    git pull
                    npm ci
                    npm run build:preview
